
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - application-networks

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: bastian@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - application-networks

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bastian_portfolio_1
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html/
      - ./environments:/etc/apache2/sites-available
    depends_on:
      - db
    restart: always
    networks:
      - application-networks

networks:
  application-networks:
    driver: bridge

volumes:
  db_data_new:
